#!/usr/bin/python3.5
import logging
import traceback
import shutil

from lit import litd
logger = logging.getLogger(__name__)

def start_daemon():
    try:
        litd.start()
    except Exception as e:
        traceback.print_exc()
        logger.critical('Uncaught exception: {}'.format(e))

if __name__ == "__main__":
    start_daemon()
